---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: default-mtls
  labels:
    istio-injection: enabled
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: baseline

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-mtls-ns-quota
  namespace: default-mtls
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 10Gi
    limits.cpu: "2"
    limits.memory: 2Gi